### ISSUE TITLE
Add support for FRC timing

### ISSUE THREAD

**Issue by spinarr** [iqrfsdk/clibdpa#21]
There is no timeout calculation for FRC cmd in v1.0.x.

**Comment by spinarr** [comment]
FRC timing is important since JS drivers are now including support for FRC cmds.
In order to calculate FRC timeout we need these params:

    // number of bonded nodes
    private final int bondedNodesNum;

    // number of discovered nodes
    private final int discoveredNodesNum;

    // RF mode
    private final RF_Mode rfMode;

    // response time on coordinator
    private final FRC_Configuration.FRC_RESPONSE_TIME reponseTime;

We also need to distinguish std and advanced FRC based on frc cmd and data lenght.

What would be best way to handle FRC timing in the daemon?
This should be done even for v1.

**Comment by logimic** [comment]
Please provide more information how the timeout is evaluated. Is it just a formula from these parameters?

We have some timeout evaluation  in clibdpa already. The problem is clibdpa don't know anything about flowing messages. The only exception is a hack for discovery and allowing infinite timeout just for this case. Introducing other hacks is not very reasonable, but I don't know better solution. So we can add another hack.

It shouldn't be problem to implement it on higher level if it it's known FRC cmd. The information about bonding numbers, etc. Shall be there anyway at least for statical purpose.

Another possibility is to turn the hack to a feature and add the state information (bonded nodes) to evaluation directly in DPA. In this case it shall systematically verify PNUM and PCMD and use predefined rules to compute the timeout.

**Comment by spinarr** [comment]
https://github.com/iqrfsdk/jsimply/blob/develop/simply-modules/simply-iqrf-dpa30x/simply-iqrf-dpa-v30x/src/main/java/com/microrisc/simply/iqrf/dpa/v30x/protocol/ProtocolStateMachine.java

L264: private static class FRC_WaitingTimeForResponseCounter extends WaitingTimeForResponseCounter {

https://github.com/iqrfsdk/jsimply/blob/develop/simply-modules/simply-iqrf-dpa30x/simply-iqrf-dpa-v30x/src/main/java/com/microrisc/simply/iqrf/dpa/v30x/protocol/timing/FRC_TimingParams.java

**Comment by spinarr** [comment]
https://github.com/iqrfsdk/clibdpa/commit/72bccc6bc7c72a9c35e8693290b834780c6a3c9c
https://github.com/iqrfsdk/clibdpa/commit/82f748f05cae3c8108b631f1402f4922a5b866a7
