### ISSUE TITLE
Improve DpaTransaction handling redesign

### ISSUE THREAD

**Issue by fmikulu** [iqrfsdk/clibdpa#23]
Merge behaviour of DpaTransaction and DpaTransfer classes to get cleaner design. 
Timing of pending Dpa transaction shall be interruptible to allow monitoring thread to check healthiness of the transaction (e.g. pet Watch Dog, provide TRC, handle async message, etc)

**Comment by spinarr** [comment]
This will be handled as part of new component for DPA?

**Comment by logimic** [comment]
BTW we have such component already: 
https://gitlab.iqrfsdk.org/gateway/iqrf-daemon/tree/master/IqrfDpa
It's a wrapper around existing clibdpa. We have to discuss and finalize interface, then it is possible to start redesign in other component implementing the same interface. When finished its easy to switch.

**Comment by michal-konopa** [comment]
In the branch feature/review-2 is the first proposal of (API) usage simplification. Concrete example is in DpaLibraryDemo::pulseLedRDpaTransaction (compare with DpaLibraryDemo::readTemperatureDpaTransaction).

**Comment by spinarr** [comment]
Initial motivation: **merge** behaviour of DpaTransaction and DpaTransfer classes to get cleaner design.
In which way is **merging** done?

**Comment by fmikulu** [comment]
Proposed redesign is in branch:
https://github.com/iqrfsdk/clibdpa/tree/feature/clibdpa2
@spinarr and @michal-konopa please review overall concept

There are still open questions:
- [x] Dpa response code is not reflected in overall result (I am not sure, but it wasn't there even in clibdpa1). Do we need it at all? It would simplify reasonably [errorCode](https://github.com/iqrfsdk/clibdpa/blob/03556c61eb0c40b093ca8b142d5ffdd76ab5b00f/Dpa/DpaHandler2.cpp#L74)
- [ ] [Exception handling](https://github.com/iqrfsdk/clibdpa/blob/03556c61eb0c40b093ca8b142d5ffdd76ab5b00f/Dpa/DpaHandler2.cpp#L496). I would propose just to end transaction in ordinary way with error code. It is related to Dpa response code in previous bullet
- [ ] [Response aditional time](https://github.com/iqrfsdk/clibdpa/blob/03556c61eb0c40b093ca8b142d5ffdd76ab5b00f/Dpa/DpaHandler2.cpp#L570) Is it necessary? It slows down communication significantly, but maybe it is necessary. But wouldn't be sufficient just a flat refresh ~40 ms?
- [ ] [Response aditional time for infinit timeout](https://github.com/iqrfsdk/clibdpa/blob/03556c61eb0c40b093ca8b142d5ffdd76ab5b00f/Dpa/DpaHandler2.cpp#L590) If required why not here?
- [ ] [estimateTimeout functions](https://github.com/iqrfsdk/clibdpa/blob/03556c61eb0c40b093ca8b142d5ffdd76ab5b00f/Dpa/DpaHandler2.cpp#L605) Passed values are already stored in the class members. Planned FRC estimation may be even worse, so simplifying the methods signature seem reasonable.
- [ ] [ServiceId](https://github.com/iqrfsdk/clibdpa/blob/03556c61eb0c40b093ca8b142d5ffdd76ab5b00f/Dpa/DpaHandler2.cpp#L819) legacy residue may be omitted - depends on future clibdpa2 deployment and relation with component design

**Comment by michal-konopa** [comment]
Some notes and questions from me:
- what about usage of namespaces?
- it is not clear to me, why there was used int32_t in the [IDpaHandler2::executeDpaTransaction](https://github.com/iqrfsdk/clibdpa/blob/03556c61eb0c40b093ca8b142d5ffdd76ab5b00f/Dpa/DpaHandler2.h#L100) for timeout and not an enum
- maybe it would be better to use  IDpaTransaction2::getResult() instead of [IDpaTransaction2::get()](https://github.com/iqrfsdk/clibdpa/blob/03556c61eb0c40b093ca8b142d5ffdd76ab5b00f/Dpa/DpaHandler2.h#L84) I think it is quite possible that the interface will be extended so meaning of the function could be more specific (for distinguishing from possible other get-functions in the future) 
- im not clear about advantages to have getRequest, getConfirmation, getResponse and theirs getXTs counterparts directly in the [transaction result](https://github.com/iqrfsdk/clibdpa/blob/03556c61eb0c40b093ca8b142d5ffdd76ab5b00f/Dpa/DpaHandler2.h#L26) interface. Isnt be better to have them in the [transaction ](https://github.com/iqrfsdk/clibdpa/blob/03556c61eb0c40b093ca8b142d5ffdd76ab5b00f/Dpa/DpaHandler2.h#L65) interface instead? Transaction result evokes to me to have mainly info about result.

**Comment by fmikulu** [comment]
Thanks for comments:

- namespace, class names, split to more files - yes it shall be improved.
- int32_t timeout it shall be dafaulted to -1 in IDpaHandler2::executeDpaTransaction(). Enum is not appropriate as user can pass any int as user timeout value - see comment above: `/// 0 > timeout - use default, 0 == timeout - use infinit, 0 < timeout - user value`.
- rename to `IDpaTransaction2::getResult()` well could be, `get()` is offen use in similar async interfaces like e.g.: http://en.cppreference.com/w/cpp/thread/future/get so just a hint to similarity, but It's matter of taste. Regarding extension - I would recommend to keep just one function here as it is specialized async object for user.
- IDpaTransactionResult2 is returned in consistent way as the result of asynchronous operation. Some code can be between executeDpaTransaction() and get() even both methods can be called from different treads. The result is complete when the object is return asynchronously and it isn't just errorCode, but response, confirmation, etc. I would rather keep transaction as a simple transaction async object and provide consistent result in returned object.

**Comment by fmikulu** [comment]
Dpa response code is propagated to errorCode by 3c3ac839b818a515740986def61054c2084d1468

**Comment by fmikulu** [comment]
Done and cleaned
