### ISSUE TITLE
Remove DpaExtension from the library

### ISSUE THREAD

**Issue by spinarr** [iqrfsdk/clibdpa#26]
- Embper and Stddev will be handled by IQRF JS drivers
- Leave simple example

**Comment by logimic** [comment]
IMHO I would keep **clibdpa** as it is, because https://github.com/iqrfsdk/iqrf-daemon depends on it (V1).

Removing **DpaExtension** or some other API changes means significant effort for V1.

However it make sense to create DPA component in https://gitlab.iqrfsdk.org/gateway/iqrf-daemon as an evolution of clibdpa without DpaExtension. Something is already there as a wrapper for existing **clibdpa**:
https://gitlab.iqrfsdk.org/gateway/iqrf-daemon/tree/master/IqrfDpa

**Comment by logimic** [comment]
In case you want to change **clibdpa** anyway. It is necessary to adapt build scripts od daemon V1 in a way it refers clibdpa V1.0.0 release instead of master branch. Maybe it is already there?

**Comment by spinarr** [comment]
I agree, we keep it as it is.
A component for DPA will be created as part of modular design of the daemon.

**Comment by spinarr** [comment]
- v1 we have covered here:
https://github.com/iqrfsdk/clibdpa/tree/release/v1.1.0

- do we need dpa extensions at master?

**Comment by fmikulu** [comment]
- we have to solve logging - options
  - discontinue clibdpa and turn it to Shape module
  - remove logging from clibdpa - original situation a year ago. BTW there is no logging in other clib*
  - solve logging via macros - if used as independent lib macros redefine logging.
- v1.1.0 has to be branch and it is necessary to update build scripts for V1 to checkout this branch. Then I remove V1 stuff from master including DpaExtensions.
- all examples in clibdpa are V1. If continue with clibdpa as a library, we have to rewrite examples
