### ISSUE TITLE
Review default timer usage

### ISSUE THREAD

**Issue by fmikulu** [iqrfsdk/clibdpa#28]
Default timer shall be used just up to confirmation or response in case of rcode != 0 (e.g. error nadr - unbonded node). After confirmation evaluated timeout shall be used or user one if it is longer.

In case of nadr == 0 - shall we use default or user?

In case of DISCOVERY nadr == 0 - use user
What about BONDED nadr == 0 - user as for DISCOVERY?

**Comment by spinarr** [comment]
- in case of nadr we have to work out timeout that works ... remember that 200ms was not enough in same cases ... if we set default timeout 500ms in configuration then we can use this default timeout 
- discovery should wait till response comes (blocks), it is difficult one since we do not know timing in advance ... if user defines timeout then use user timeout otherwise block. 
- bonding blocks for 10s so max wait 11s if user defines timeout then use user timeout

**Comment by fmikulu** [comment]
Solve together with https://gitlab.iqrfsdk.org/gateway/iqrf-daemon/issues/121
